### ISSUE TITLE
Raspbian 9.1 and Jarvis

### ISSUE THREAD

**Issue by adoublard** [Kitt-AI/snowboy#265] opened 2017-08-28 14:42 UTC
Hi, from Jarvis (https://github.com/alexylem/jarvis) it's recommanded to use Snowboy but the install fail on my Raspbian 9.1 on raspberry pi 3b.

If someone could help me to make it working ..

**Comment by evancohen** [comment] 2017-08-28 18:42
Not much to go on here. It'd be great if you could describe what your issue is. If the installation for jarvis is the problem then you should start by filing an issue on that repository fist.  
One thing you might try is installing snowboy on your Pi standalone (without Jarvis) to see if that's the problem.

**Comment by adoublard** [comment] 2017-08-28 18:55
The problem is not jarvis, it work well but i can't install snowboy at all, it say 
![capture](https://user-images.githubusercontent.com/31312065/29788473-017b5f26-8c33-11e7-8cc8-1dddc935c687.JPG)
and i do not understand why it would work on raspbian 8 jessie and not on rapbian 9.1 jessie, i tryed manual install but the result is the same..

**Comment by chenguoguo** [comment] 2017-08-29 01:14
The message comes from Jarvis not from Snowboy. It's possible that Snowboy works on 9.1, but Jarvis "thinks" it doesn't work on that.

**Comment by Oliv4945** [comment] 2017-08-29 11:43
Hi, the problem is from Jarvis which restricts (for now) the installation to Raspbian 8.
You can close the issue.

Reference [here ](https://github.com/alexylem/jarvis/issues/707)(in French)

**Comment by chenguoguo** [comment] 2017-08-29 11:56
Thanks, closing it.

**Closed by chenguoguo** 2017-08-29 11:56 UTC
