### ISSUE TITLE
Android platform

### ISSUE THREAD

**Issue by caohaoping** [Kitt-AI/snowboy#142] opened 2017-03-11 03:53 UTC
The integration tutorial on Android is too simple, you can step by step and then detailed?

**Comment by xuchen** [comment] 2017-03-11 04:27
Duplicate of https://github.com/Kitt-AI/snowboy/issues/106

What's your Android platform and CPU? We currently have a more detailed version but it won't come out until next week.

**Closed by xuchen** 2017-03-11 04:27 UTC

**Comment by xuchen** [comment] 2017-03-20 20:53
@caohaoping I worked on the https://github.com/Kitt-AI/snowboy/tree/android-demo branch and pushed a demo there. Could you please check it out and give comments?

https://github.com/Kitt-AI/snowboy/blob/android-demo/examples/Android/README.md

I'll merge this branch in about a week's time. Your opinion on this is much appreciated.
